#Exercise 13
#Write a program that asks the user how many fibonacci numbers to generate and
#then generates them.
#Try to use functions !!
#Make sure to ask the user to enter the number of numbers in the sequence to
#generate
#Hint: -
#The Fibonacci numbers are generated by setting F0=0, F1=1, and then using the recursive formula
#Fn = Fn-1 + Fn-2
#Fibonacci series: - 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144----so on.


def fibo(n):
    if n == 0:
        return 0
    elif n == 1:        
        return 1
    else:
        return fibo(n-1)+ fibo(n-2)       
    
attempts = int(input('Which fibonacci number do you want to generate:'))

result = fibo(attempts)
print('Fibonacci of {} elements is {}'.format(attempts,result))
